**Numpy**
- numerical python
- Extension package to python for multidementional arrays
- designed for scientific computation (convenience)
- also known as array oriented computing
- homogeneous (same kind of datatypes)

**Advantages of array**
- less memory
- fast (closet to hardware)
- conenience

In [1]:
import numpy as np

In [17]:
# one dimentional array
a=np.array([1,23,4,9.87])
type(a)

numpy.ndarray

In [18]:
a.dtype

dtype('float64')

In [19]:
a

array([ 1.  , 23.  ,  4.  ,  9.87])

In [27]:
# slicing function
b=np.array([1,2,3,4,5,6,7])
print(b[0])
print(b[-1])
print(b[1:5])
print(b[[1,5]])
print(b[2:])
print(b[0::2])

1
7
[2 3 4 5]
[2 6]
[3 4 5 6 7]
[1 3 5 7]


In [34]:
# Iteration procedural 
print(np.arange(10))
print(np.arange(4,13))
print(np.arange(2,10,3))

[0 1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11 12]
[2 5 8]


In [29]:
c

range(1, 50)

In [38]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [42]:
c=range(1,100)
%timeit [i**5 for i in c]

64.5 µs ± 23.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [43]:
c_numpy=np.arange(1000)
%timeit c_numpy**5

5.83 µs ± 2.25 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [47]:
c=range(1000)
d=[i**2 for i in c]

%timeit list(map(lambda x,y:x*y,c,d))

224 µs ± 63 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [51]:
c_numpy = np.array(c)
d_numpy = np.array(d)

%timeit c_numpy * d_numpy

2.47 µs ± 633 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [45]:
d=[]
for i in range(1000):
    d=i
e=[i**2 for i in c]
d*e

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 

In [57]:
# two dimentional array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
a[0:,0:1]  # 1 =row(0)
            # 4 =row(1)
            # 7 =row(2)

array([[1],
       [4],
       [7]])

In [73]:
#[2,3]
#[5,6]

a[0:2,1:]

array([[2, 3],
       [5, 6]])

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
- square matrix
- null matrix
- identity matrix
- Rectangular matrix
- diagnoal matrix
- Transpose matrix
- inverse matrix


In [77]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [79]:
# null matrix
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
a.shape

(3, 3)

In [81]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
np.full((2,2),6)

array([[6, 6],
       [6, 6]])

In [84]:
np.diag([2,5,3,6,4])

array([[2, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 4]])

In [85]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [88]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
a.shape

(2, 3)

In [90]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [93]:
np.linalg.inv(b)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [169]:
# random function
a=30*np.random.random((3,3))+5
a

array([[ 5.34575376, 19.22854745, 19.39539101],
       [32.64888242, 21.40298859, 23.6733762 ],
       [12.85605171, 17.14662568, 14.09339711]])

In [172]:
np.round(a)

array([[ 5., 19., 19.],
       [33., 21., 24.],
       [13., 17., 14.]])

In [175]:
np.random.randint(1,20,[3,3])

array([[ 9,  7,  4],
       [14, 17, 10],
       [11,  4, 16]])

In [186]:
np.random.randn(3,3)

array([[ 0.04207033, -0.50277913,  0.37291479],
       [ 1.41019562,  1.63039213, -0.17196419],
       [-0.45465635,  0.06892819, -1.64736878]])

In [187]:
np.random.choice(["a","b","c","d"],20)

array(['a', 'd', 'c', 'a', 'd', 'a', 'a', 'a', 'c', 'a', 'b', 'b', 'c',
       'd', 'c', 'c', 'd', 'a', 'b', 'a'], dtype='<U1')

In [193]:
a=np.linspace(1,50,30)
a

array([ 1.        ,  2.68965517,  4.37931034,  6.06896552,  7.75862069,
        9.44827586, 11.13793103, 12.82758621, 14.51724138, 16.20689655,
       17.89655172, 19.5862069 , 21.27586207, 22.96551724, 24.65517241,
       26.34482759, 28.03448276, 29.72413793, 31.4137931 , 33.10344828,
       34.79310345, 36.48275862, 38.17241379, 39.86206897, 41.55172414,
       43.24137931, 44.93103448, 46.62068966, 48.31034483, 50.        ])

In [ ]:
1*2*3*4*5
11*12*13*14*15
21*22*23*24*25
16*17*18*19*20
6*7*8*9*10

In [200]:
c=1
for i in range(1,6):
    for j in range(1,6):
        print('{:02}'.format(c),end="*")
        c=c+1
    print(end="\n")

01*02*03*04*05*
06*07*08*09*10*
11*12*13*14*15*
16*17*18*19*20*
21*22*23*24*25*
